import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { useSelector } from 'react-redux';
import { authSlice, selectAuthState } from '@/store/authSlide';
import { useDispatch } from 'react-redux/es/exports';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const auth = useSelector(selectAuthState);
  const dispatch = useDispatch();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>{auth ? <h2>log</h2> : <h2>out</h2>}</div>
          <div>
            <button
              onClick={() => {
                dispatch(authSlice.actions.setAuthState(true));
              }}
            >
              login
            </button>
          </div>
          <div>
            <button
              onClick={() => {
                dispatch(authSlice.actions.setAuthState(false));
              }}
            >
              logout
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
