import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { useDispatch, useSelector } from 'react-redux';
import { selectAuthState, setAuthState } from '@/store/authSlider';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const authState = useSelector(selectAuthState);
  const dispatch = useDispatch();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {authState ? <h2>hello world</h2> : <h2>im out</h2>}
          <div>
            <button
              onClick={() => {
                dispatch(setAuthState(true));
              }}
            >
              login
            </button>
          </div>
          <div>
            <button
              onClick={() => {
                dispatch(setAuthState(false));
              }}
            >
              logout
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
